name: Deploy to Firebase

# DISABLED: Firebase Functions removed (free tier limitation)
# Using Vercel for hosting + Firebase for database/storage only
# This workflow is disabled to prevent unnecessary deployments
on:
  workflow_dispatch:
    inputs:
      confirm_disable:
        description: 'This workflow is disabled. Firebase hosting not needed with Vercel.'
        required: true
        default: 'disabled'

jobs:
  disabled:
    runs-on: ubuntu-latest
    steps:
      - name: Workflow Disabled Notice
        run: |
          echo "🚫 Firebase hosting deployment is DISABLED"
          echo "Reason: Using Vercel for hosting, Firebase only for backend services"
          echo "If you need to re-enable, remove the 'workflow_dispatch' trigger"
          exit 1
